### ISSUE TITLE
Stipend Implementation

### ISSUE THREAD

**Issue by maennchen** [erlef/oidcc_plug#1]
Part of https://github.com/Erlang-Openid/oidcc/issues/221

## Requirements

* [X] Good Test Coverage
* [X] Good Code Quality
* [X]  Secure Defaults
  * [X] ~~Shipped with a secure and complete TLS setup~~ OTP 26 ships with one
  * [X] Can be overridden with custom TLS settings
  * [X] JWT Settings are automatically set up to the most strict settings according to the OIDC Config Introspection
* [x] GitHub Actions Setup that runs
  * [X] Unit Tests
  * [X] Linter
  * [X] Dialyzer
* [X] All libraries are well documented on Hex
  * [X] public functions have dialyzer specs
  * [X] public functions have examples
  * [X] contains setup instructions
  * [x] contains examples for most common use cases
* [x] oidcc Configuration Processes provide an elixir compatible child_spec so that they can be started easily
* [X] Compatible with latest stable OTP / Elixir releases at time of publication

## TODO

* [x] Provide code flow plugs - #3 
* [x] Allow runtime plug config - #4
* [x] Move repos to @erlef - @peerst
* [x] Re-Enable coveralls.io - @peerst 
* [x] Implement cache put
* [x] Public Testing
* [x] Stable Release
